package com.krypton.onlineFundTransaction.constants;

public enum EnumFailureReasons {
	INTERNAL_ERROR,
	DAILY_LIMIT,
	MONTHLY_LIMIT,
	INSUFFICIENT_BALANCE,
	INVALID_SOURCE_ACCOUNT,
	INVALID_DESTINATION_ACCOUNT,
	INVALID_CIF,
	INVALID_CURRENCY,
	INVALID_REASON,
	INACTIVE_ACCOUNT
}
